### ISSUE TITLE
A problem occurred evaluating root project 'RetailAttendanceMonitor'

### ISSUE THREAD

**Issue by Er-Anil** [Chumbak/Retailstore-Attendance-Monitor#4]
I'm trying to run this project but getting an error  please suggest me where I'm doing wrong.

Scanning 722 folders for symlinks in E:\Office\ReactNativeProjects\Retailstore-Attendance-Monitor-master\node_modules (110ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat install Debug)...

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\Office\ReactNativeProjects\Retailstore-Attendance-Monitor-master\                     android\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'RetailAttendanceMonitor'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or -- debug option to get more log output.

BUILD FAILED

Total time: 9.729 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by harshattray** [comment]
This seems to be occurring due to difference in the version of the gradle distribution url . In the project we use 2.14.1. 

In the  `gradle-wrapper.properties`
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

In the set build.gradle change 
```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }
}
```

We are basically adding the `google()` dependancy here.

In the ` in android/app/build.gradle` update the `compileSdkVersion`  and `buildToolsVersion`

```
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.0"
    ...
```
This should fix the above error.

**Comment by harshattray** [comment]
I'm closing this issue for now as the above solution seems optimal. Let us know if the issue persists
